apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-batch.fullname" . }}-consumer
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ include "kafka-batch.fullname" . }}-consumer
