apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kafka-batch.fullname" . }}-kafka-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.kafka.storage.size }}
