apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-batch.fullname" . }}-kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: {{ include "kafka-batch.fullname" . }}-kafka
