apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-batch.fullname" . }}-zk
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: {{ include "kafka-batch.fullname" . }}-zk
